services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "${SA_PASSWORD}"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      # - ./docker/sql:/docker-entrypoint-initdb.d


  eshopservice:
    build:
      context: .
      dockerfile: .\EShopService\Dockerfile
    depends_on:
      - db
    environment:
      - CONNECTION_STRING=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
      # - ConnectionStrings__DefaultConnection=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};TrustServerCertificate=True;
    ports:
      - "8080:8080"
  
  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    depends_on:
      - db
    environment:
      - CONNECTION_STRING=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};Encrypt=False;TrustServerCertificate=True;
      # - ConnectionStrings__DefaultConnection=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};TrustServerCertificate=True;
    build:
      context: .
      dockerfile: UserService/Dockerfile

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
      
  

volumes:
  mssql_data: