services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "YourPassword123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./docker/sql:/docker-entrypoint-initdb.d
    command: >
      /bin/bash -c "
        /opt/mssql/bin/sqlservr & 
        sleep 20; 
        /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P ${SA_PASSWORD} -i /docker-entrypoint-initdb.d/init.sql; 
        wait"


  eshopservice:
    build:
      context: .
      dockerfile: .\EShopService\Dockerfile
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST};Database=${DB_NAME};User Id=${DB_USER};Password=${SA_PASSWORD};TrustServerCertificate=True;
    ports:
      - "8080:8080"
      
  

volumes:
  mssql_data: